#
# Variables
#

substitutions:
  device_id: garage_light
  device_name: garage-light
  friendly_name: Garage Light

esphome:
  name: "${device_name}"

#
# Networking
#

# <SNIP>

#
# Real ESP configuration
# Base: KS-602S
#

#
# Real ESP configuration
# Base: KS 602S
#

# Board
esp8266:
  board: esp01_1m

# Enable logging
logger:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    id: "${device_id}_button"
    on_press:
      - switch.toggle: "${device_id}_relay"
  - platform: status
    name: "${friendly_name} Status"
    id: "${device_id}_status"

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    id: "${device_id}_relay"
    pin: GPIO12
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

output:
  - platform: gpio
    pin: GPIO13
    inverted: true
    id: led

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi signal"
    id: "${device_id}_wifi_signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: "${device_id}_uptime"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"
    id: "${device_id}_esphome_version"
