# This is a stub file only used for tests

wifi_ssid: test
wifi_password: "12345678"
wifi_ap_password: "12345678"

christmas_outdoor_lights_encryption_key: MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAo=
christmas_outdoor_lights_ota_password: