#
# Custom CO2 sensor with a Wemos D1 + MH-Z19B
#

substitutions:
  device_id: yoann_office_co2_sensor
  device_name: yoann-office-co2-sensor
  friendly_name: CO2 Sensor @ Yoann Office

esphome:
  name: "${device_name}"
  comment: "${friendly_name}"

esp8266:
  board: esp01_1m

<<: !include {
  file: "common/networking.yaml",
  vars: {
    device_id: "${device_id}",
    wifi_ssid: !secret wifi_ssid,
    wifi_password: !secret wifi_password,
    wifi_ap_password: !secret wifi_ap_password,
    encryption_key: !secret yoann_office_co2_sensor_encryption_key,
    ota_password: !secret yoann_office_co2_sensor_ota_password,
  }
}

logger:
  baud_rate: 0 # Disable UART logging

# Configure UART (i.e. where is RX and TX on the ESP)
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  # Configure the MH-Z19 sensor
  - platform: mhz19
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false
  - !include ./common/sensor.wifi_signal.yaml
  - !include ./common/sensor.uptime.yaml

text_sensor:
  - !include ./common/text_sensor.version.yaml
