substitutions:
  device_id: yoann_office_light
  device_name: yoann-office-light
  friendly_name: Yoann Office Light

<<: !include {
  file: "common/networking.yaml",
  vars: {
    device_id: "${device_id}",
    wifi_ssid: !secret wifi_ssid,
    wifi_password: !secret wifi_password,
    wifi_ap_password: !secret wifi_ap_password,
    encryption_key: !secret christmas_tree_encryption_key,
    ota_password: !secret christmas_tree_ota_password,
  }
}

<<: !include templates/gosund-wp5.yaml