substitutions:
  device_id: _3d_printer
  device_name: 3d-printer
  friendly_name: 3D Printer

<<: !include {
  file: "common/networking.yaml",
  vars: {
    device_id: "${device_id}",
    wifi_ssid: !secret wifi_ssid,
    wifi_password: !secret wifi_password,
    wifi_ap_password: !secret wifi_ap_password,
    encryption_key: !secret _3d_printer_encryption_key,
    ota_password: !secret _3d_printer_ota_password,
  }
}

<<: !include templates/gosund-wp5.yaml