substitutions:
  device_id: christmas_outdoor_lights
  device_name: christmas-outdoor-lights
  friendly_name: Christmas Outdoor Lights

<<: !include {
  file: "common/networking.yaml",
  vars: {
    device_id: "${device_id}",
    wifi_ssid: !secret wifi_ssid,
    wifi_password: !secret wifi_password,
    wifi_ap_password: !secret wifi_ap_password,
    encryption_key: !secret christmas_outdoor_lights_encryption_key,
    ota_password: !secret christmas_outdoor_lights_ota_password,
  }
}

<<: !include templates/teckin-sp10.yaml