substitutions:
  device_id: yoann_office_meetings_lights
  device_name: yoann-office-meeting-lights
  friendly_name: Meetings Lights @ Yoann Office

<<: !include {
  file: "common/networking.yaml",
  vars: {
    device_id: "${device_id}",
    wifi_ssid: !secret wifi_ssid,
    wifi_password: !secret wifi_password,
    wifi_ap_password: !secret wifi_ap_password,
    encryption_key: !secret yoann_office_meetings_lights_encryption_key,
    ota_password: !secret yoann_office_meetings_lights_ota_password,
  }
}

<<: !include templates/gosund-wp5.yaml