substitutions:
  device_id: garage_light
  device_name: garage-light
  friendly_name: Garage Light

<<: !include {
  file: "common/networking.yaml",
  vars: {
    device_id: "${device_id}",
    wifi_ssid: !secret wifi_ssid,
    wifi_password: !secret wifi_password,
    wifi_ap_password: !secret wifi_ap_password,
    encryption_key: !secret garage_light_encryption_key,
    ota_password: !secret garage_light_ota_password,
  }
}

<<: !include templates/ks-602s.yaml