#
# Extensible Lilygo T-Relay-8 ESP32 controller for the shed
#

substitutions:
  device_id: shed_controller
  device_name: shed-controller
  friendly_name: Shed Controller

esphome:
  name: "${device_name}"
  comment: "${friendly_name}"

esp32:
  board: esp32dev

<<: !include {
  file: "common/networking.yaml",
  vars: {
    device_id: "${device_id}",
    wifi_ssid: !secret wifi_ssid,
    wifi_password: !secret wifi_password,
    wifi_ap_password: !secret wifi_ap_password,
    encryption_key: !secret shed_controller_encryption_key,
    ota_password: !secret shed_controller_ota_password,
  }
}

logger:
  baud_rate: 0 # Disable UART logging

# Status led
status_led:
  pin:
    number: GPIO25

# Relays
switch:
  - platform: gpio
    pin: GPIO33
    id: "${device_id}_relay_1"
    name: "${friendly_name} Relay 1"
  - platform: gpio
    pin: GPIO32
    id: "${device_id}_relay_2"
    name: "${friendly_name} Relay 2"
  - platform: gpio
    pin: GPIO13
    id: "${device_id}_relay_3"
    name: "${friendly_name} Relay 3"
  - platform: gpio
    pin: GPIO12
    id: "${device_id}_relay_4"
    name: "${friendly_name} Relay 4"
  - platform: gpio
    pin: GPIO21
    id: "${device_id}_relay_5"
    name: "${friendly_name} Relay 5"
  - platform: gpio
    pin: GPIO19
    id: "${device_id}_relay_6"
    name: "${friendly_name} Relay 6"
  - platform: gpio
    pin: GPIO18
    id: "${device_id}_relay_7"
    name: "${friendly_name} Relay 7"
  - platform: gpio
    pin: GPIO5
    id: "${device_id}_relay_8"
    name: "${friendly_name} Relay 8"

#
# VE.direct
# via https://github.com/KinDR007/VictronMPPT-ESPHOME
#

external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
  - source: github://KinDR007/VictronSmartShunt-ESPHOME@main

uart:
  # MPTT Charge Controller
  - id: uart0
    rx_pin: GPIO14
    baud_rate: 19200
    rx_buffer_size: 256
  # Smart Shunt
  - id: uart1
    rx_pin: GPIO15
    baud_rate: 19200
    stop_bits: 1
    data_bits: 8
    parity: NONE
    rx_buffer_size: 256

# MPTT Charge Controller
victron:
  id: victron0
  uart_id: uart0
  throttle: 10s # real is 1 datapoint per minute

# Smart Shunt
victron_smart_shunt:
  uart_id: uart1

# Sensors
sensor:
  - !include ./common/sensor.wifi_signal.yaml
  - !include ./common/sensor.uptime.yaml

  # MPTT Charge Controller
  - platform: victron
    victron_id: victron0
    max_power_yesterday:
      name: "${friendly_name} Charge Controller: max power yesterday"
    max_power_today:
      name: "${friendly_name} Charge Controller: max power today"
    yield_yesterday:
      name: "${friendly_name} Charge Controller: yield yesterday"
    yield_total:
      name: "${friendly_name} Charge Controller: yield total"
    panel_voltage:
      name: "${friendly_name} Charge Controller: panel voltage"
    panel_power:
      name: "${friendly_name} Charge Controller: panel power"
    battery_voltage:
      name: "${friendly_name} Charge Controller: battery voltage"
    battery_current:
      name: "${friendly_name} Charge Controller: panel current"
    day_number:
      name: "${friendly_name} Charge Controller: day number"
    charging_mode_id:
      name: "${friendly_name} Charge Controller: charging mode id"
    error_code:
      name: "${friendly_name} Charge Controller: error code"
    tracking_mode_id:
      name: "${friendly_name} Charge Controller: tracking mode id"
    load_current:
      name: "${friendly_name} Charge Controller: load current"

  # Smart Shunt
  - platform: victron_smart_shunt
    battery_voltage:
      name: "${friendly_name} Shunt: battery voltage"
    battery_current:
      name: "${friendly_name} Shunt: battery current"
    fw_version:
      name: "${friendly_name} Shunt: firmware version"

text_sensor:
  - !include ./common/text_sensor.version.yaml

  # MPTT Charge Controller
  - platform: victron
    victron_id: victron0
    charging_mode:
      name: "${friendly_name} Victron: charging mode"
    error:
      name: "${friendly_name} Victron: error"
    tracking_mode:
      name: "${friendly_name} Victron: tracking mode"
    firmware_version:
      name: "${friendly_name} Victron: firmware version"
    device_type:
      name: "${friendly_name} Victron: device type"
    serial_number:
      name: "${friendly_name} Victron: serial number"
