#
# Variables
#

substitutions:
  device_id: frontdoor_light
  device_name: frontdoor-light
  friendly_name: Frontdoor Light

esphome:
  name: "${device_name}"

#
# Networking
#

# <SNIP>

#
# Real ESP configuration
# Base: KS-7012
#

# Board
esp8266:
  board: esp01_1m

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Configure UARD
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

light:
  - platform: tuya
    id: "${device_id}_light"
    name: "${friendly_name}"
    dimmer_datapoint: 2 # where is the dimmer
    switch_datapoint: 1 # where is the switch
    min_value: 42 # min value for the dimmer
    max_value: 255 # max value for the dimmer

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi signal"
    id: "${device_id}_wifi_signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: "${device_id}_uptime"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"
    id: "${device_id}_esphome_version"
