esp8266:
  board: esp01_1m

esphome:
  name: "${device_name}"
  comment: "${friendly_name} (Teckin SP10 smart outlet)"

logger:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    id: "${device_id}_button"
    on_press:
      - switch.toggle: "${device_id}_relay"
  - platform: status
    name: "${friendly_name} Status"
    id: "${device_id}_status"

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    id: "${device_id}_relay"
    pin: GPIO15
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

status_led:
  pin:
    number: GPIO00
    inverted: yes

output:
  - platform: gpio
    pin: GPIO02
    inverted: true
    id: led

sensor:
  - !include ../common/sensor.wifi_signal.yaml
  - !include ../common/sensor.uptime.yaml

text_sensor:
  - !include ../common/text_sensor.version.yaml
